version: '2.1'
services:
  live-reload:
    image: spotify-streamdeck
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - live-reload
    volumes:
      - .:/spotify-streamdeck
      - node_modules:/spotify-streamdeck/node_modules
    ports:
      - 3000:3000
volumes:
  node_modules: {}
